### ISSUE TITLE
Training script 작성

### ISSUE THREAD

**Issue by chanil1218** [chanil1218/Attention-SE.pytorch#2]
아직 구현되지 않은 Attention 모델 대신 비교군으로 사용할 DCUnet model을 사용하고, 
추후에 구현할 Attention model 을 넣어서 학습할 수 있도록.

**Comment by rownrrns** [comment]
Data loader, tensorboard logging 파트가 있다고 생각하고 script를 짠다.

Reference URL :
-DCU Net
  https://github.com/chanil1218/DCUnet.pytorch/blob/master/train.py#L100
-DCU Net 2
  https://github.com/sweetcocoa/DeepComplexUNetPyTorch

**Comment by chanil1218** [comment]
음성파일을 spectrogram feature 로 바꾸는 파트의 경우에는 DCUnet.pytoch 경우에는 layer 로 되어있음. Data loader에서 train/test/eval 모두 noisy speech 와 clean speech의 audio 혹은 filename? 이 들어온다고 생각하고 STFT나 ISTFT 으로 Feature extraction 하는 부분까지 model에서 처리해줘야 할 것 같아요. 

Loader에 audio를 받을지 filename 으로 받을 지는 @ddw02141 와 얘기해서 조율하면 좋을 것 같아요.

**Comment by chanil1218** [comment]
DCUnet.pytorch model을 /models/ 아래로 가져오고 저 모델을 학습하는 스크립트를 짜주시면 제가 models/ 아래에 attention_se.py 같은 모델을 추가할게요. DCUnet.pytorch 모델이랑 유사한 구조로. 

https://github.com/chanil1218/DCUnet.pytorch

**Comment by rownrrns** [comment]
Feature extraction 하는 부분을 model에서 해야한다는건 model 만들때 한다는건가요 아니면 training에서 한다는 건가요?

**Comment by chanil1218** [comment]
@rownrrns https://github.com/chanil1218/DCUnet.pytorch/blob/master/train.py#L31
train script에서 해주시면 될 것 같습니다.
